import sys


import pandas as pd

# in_f  = '/oak/stanford/groups/mrivas/ukbb24983/array-combined/annotation/annotation_20201012/ukb24983_cal_hla_cnv.annot_20201023.tsv.gz'
# out_f = '/oak/stanford/groups/mrivas/ukbb24983/array-combined/annotation/annotation_20201012/ukb24983_cal_hla_cnv.annot_20201023.feather'

def get_dtype_var_annotation():
    return {
        '#CHROM'           : 'str',
        'CHROM'            : 'str',
        'POS'              : 'int64',
        'ID'               : 'str',
        'REF'              : 'str',
        'ALT'              : 'str',
        'FILTER'           : 'category',
        'POS_total'        : 'int64',        
        'CHROM_hg19'       : 'str',
        'POS_hg19'         : 'float64',
        'REF_hg19'         : 'str',
        'ALT_hg19'         : 'str',
        'CHROM_hg38'       : 'str',
        'POS_hg38'         : 'float64',
        'REF_hg38'         : 'str',
        'ALT_hg38'         : 'str',
        'liftOver_unmapped_reason' : 'category',
        'Allele'           : 'str',
        'Csq'              : 'category',
        'Consequence'      : 'category',
        'SYMBOL'           : 'str',
        'Gene'             : 'str',
        'ld_indep'         : 'bool',
        'geno_data_source' : 'category',
        'array'            : 'category',
        'CNV_POS_s'        : 'float64',
        'CNV_POS_e'        : 'float64',
        'UKB_white_british_MAF' : 'float64',
        'hwe_p'            : 'float64',
        'mgi_notes'        : 'str',
        'f_miss'           : 'float64',
        'f_miss_UKBB'      : 'float64',
        'f_miss_UKBL'      : 'float64',
        'LoF'              : 'category',
        'LoF_filter'       : 'category',
        'LoF_flags'        : 'category',
        'LoF_info'         : 'str',
        'IMPACT'           : 'category',
        'Feature_type'     : 'category',
        'Feature'          : 'str',
        'BIOTYPE'          : 'str',
        'EXON'             : 'str',
        'INTRON'           : 'str',
        'HGVSc'            : 'str',
        'HGVSp'            : 'str',
        'cDNA_position'    : 'str',
        'CDS_position'     : 'str',
        'Protein_position' : 'str',
        'Amino_acids'      : 'str',
        'Codons'           : 'str',
        'Existing_variation' : 'str',
        'ALLELE_NUM'       : 'float64',
        'DISTANCE'         : 'str',
        'STRAND'           : 'category',
        'FLAGS'            : 'category',
        'VARIANT_CLASS'    : 'category',
        'SYMBOL_SOURCE'    : 'category',
        'HGNC_ID'          : 'str',
        'CANONICAL'        : 'category',
        'MANE'             : 'category',
        'TSL'              : 'category',
        'APPRIS'           : 'category',
        'CCDS'             : 'str',
        'ENSP'             : 'str',
        'SWISSPROT'        : 'str',
        'TREMBL'           : 'str',
        'UNIPARC'          : 'str',
        'GENE_PHENO'       : 'float64',
        'SIFT'             : 'str',
        'PolyPhen'         : 'str',
        'DOMAINS'          : 'str',
        'miRNA'            : 'category',
        'HGVS_OFFSET'      : 'float64',
        'AF'               : 'float64',
        'AFR_AF'           : 'float64',
        'AMR_AF'           : 'float64',
        'EAS_AF'           : 'float64',
        'EUR_AF'           : 'float64',
        'SAS_AF'           : 'float64',
        'AA_AF'            : 'float64',
        'EA_AF'            : 'float64',
        'gnomAD_AF'        : 'float64',
        'gnomAD_AFR_AF'    : 'float64',
        'gnomAD_AMR_AF'    : 'float64',
        'gnomAD_ASJ_AF'    : 'float64',
        'gnomAD_EAS_AF'    : 'float64',
        'gnomAD_FIN_AF'    : 'float64',
        'gnomAD_NFE_AF'    : 'float64',
        'gnomAD_OTH_AF'    : 'float64',
        'gnomAD_SAS_AF'    : 'float64',
        'MAX_AF'           : 'float64',
        'MAX_AF_POPS'      : 'str',
        'CLIN_SIG'         : 'category',
        'SOMATIC'          : 'category',
        'PHENO'            : 'category',
        'PUBMED'           : 'str',
        'VAR_SYNONYMS'     : 'str',
        'MOTIF_NAME'       : 'str',
        'MOTIF_POS'        : 'str',
        'HIGH_INF_POS'     : 'category',
        'MOTIF_SCORE_CHANGE'    : 'str',
        'TRANSCRIPTION_FACTORS' : 'str',
        'UKB_AF'           : 'float64',
        'UKB_white_british_AF'     : 'float64',
        'UKB_non_british_white_AF' : 'float64',
        'UKB_african_AF'   : 'float64',
        'UKB_s_asian_AF'   : 'float64',
        'UKB_e_asian_AF'   : 'float64',
        'UKB_related_AF'   : 'float64',
        'UKB_others_AF'    : 'float64',
        'UKB_hwe_p'        : 'float64',
        'UKB_white_british_hwe_p'     : 'float64',
        'UKB_non_british_white_hwe_p' : 'float64',
        'UKB_african_hwe_p'  : 'float64',
        'UKB_s_asian_hwe_p'  : 'float64',
        'UKB_e_asian_hwe_p'  : 'float64',
        'UKB_related_hwe_p'  : 'float64',
        'UKB_others_hwe_p'   : 'float64',
        'UKB_OBS_CT'         : 'int64',
        'UKB_white_british_OBS_CT'     : 'int64',
        'UKB_non_british_white_OBS_CT' : 'int64',
        'UKB_african_OBS_CT' : 'int64',
        'UKB_s_asian_OBS_CT' : 'int64',
        'UKB_e_asian_OBS_CT' : 'int64',
        'UKB_related_OBS_CT' : 'int64',
        'UKB_others_OBS_CT'  : 'int64',
        'UKB_UKBB_OBS_CT'    : 'int64',
        'UKB_UKBL_OBS_CT'    : 'int64',
        'UKB_MISSING_CT'     : 'int64',
        'UKB_white_british_MISSING_CT'     : 'int64',
        'UKB_non_british_white_MISSING_CT' : 'int64',
        'UKB_african_MISSING_CT' : 'int64',
        'UKB_s_asian_MISSING_CT' : 'int64',
        'UKB_e_asian_MISSING_CT' : 'int64',
        'UKB_related_MISSING_CT' : 'int64',
        'UKB_others_MISSING_CT'  : 'int64',
        'UKB_UKBB_MISSING_CT'    : 'int64',
        'UKB_UKBL_MISSING_CT'    : 'int64',
        'UKB_HOM_REF_CT'         : 'int64',
        'UKB_white_british_HOM_REF_CT'     : 'int64',
        'UKB_non_british_white_HOM_REF_CT' : 'int64',
        'UKB_african_HOM_REF_CT' : 'int64',
        'UKB_s_asian_HOM_REF_CT' : 'int64',
        'UKB_e_asian_HOM_REF_CT' : 'int64',
        'UKB_related_HOM_REF_CT' : 'int64',
        'UKB_others_HOM_REF_CT'  : 'int64',
        'UKB_HET_REF_ALT_CTS'    : 'int64',
        'UKB_white_british_HET_REF_ALT_CTS'     : 'int64',
        'UKB_non_british_white_HET_REF_ALT_CTS' : 'int64',
        'UKB_african_HET_REF_ALT_CTS' : 'int64',
        'UKB_s_asian_HET_REF_ALT_CTS' : 'int64',
        'UKB_e_asian_HET_REF_ALT_CTS' : 'int64',
        'UKB_related_HET_REF_ALT_CTS' : 'int64',
        'UKB_others_HET_REF_ALT_CTS'  : 'int64',
        'UKB_TWO_ALT_GENO_CTS'        : 'int64',
        'UKB_white_british_TWO_ALT_GENO_CTS'     : 'int64',
        'UKB_non_british_white_TWO_ALT_GENO_CTS' : 'int64',
        'UKB_african_TWO_ALT_GENO_CTS' : 'int64',
        'UKB_s_asian_TWO_ALT_GENO_CTS' : 'int64',
        'UKB_e_asian_TWO_ALT_GENO_CTS' : 'int64',
        'UKB_related_TWO_ALT_GENO_CTS' : 'int64',
        'UKB_others_TWO_ALT_GENO_CTS'  : 'int64',
        'UKB_HAP_REF_CT'               : 'int64',
        'UKB_white_british_HAP_REF_CT'     : 'int64',
        'UKB_non_british_white_HAP_REF_CT' : 'int64',
        'UKB_african_HAP_REF_CT' : 'int64',
        'UKB_s_asian_HAP_REF_CT' : 'int64',
        'UKB_e_asian_HAP_REF_CT' : 'int64',
        'UKB_related_HAP_REF_CT' : 'int64',
        'UKB_others_HAP_REF_CT'  : 'int64',
        'UKB_HAP_ALT_CTS'        : 'int64',
        'UKB_white_british_HAP_ALT_CTS'     : 'int64',
        'UKB_non_british_white_HAP_ALT_CTS' : 'int64',
        'UKB_african_HAP_ALT_CTS' : 'int64',
        'UKB_s_asian_HAP_ALT_CTS' : 'int64',
        'UKB_e_asian_HAP_ALT_CTS' : 'int64',
        'UKB_related_HAP_ALT_CTS' : 'int64',
        'UKB_others_HAP_ALT_CTS'  : 'int64'
    }
    

def tsvgz2feather(in_f, out_f, delimiter='\t', dtype=None):    
    pd.read_csv(
        in_f, sep=delimiter, dtype=dtype
    ).rename(
        columns = {'#CHROM' : 'CHROM'}
    ).to_feather(
        out_f,
        compression='zstd'
    )


if __name__ == '__main__':
    in_f     = sys.argv[1]
    out_f    = sys.argv[2]
    tsvgz2feather(in_f, out_f, delimiter='\t', dtype=get_dtype_var_annotation())
